---
- name: This is a hello-world example
  hosts: localhost

  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile.txt    
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile1.txt  
    - name: facts
      copy:
        content: file
        dest: /tmp/testfile2.txt
    - name: execute shell
      shell: cd /Users/nitishkumar/Desktop/ansibel/ansible && sh  tesh.sh
      register: output
    - debug:
        var: output
    - ping:

  




